Stick to using npm@8 (not v9) for running tests.
This should fix the following error in Node.js 12 using npm@9:

  ERROR: npm v9.1.1 is known not to run on Node.js v12.22.12. You'll need to
  upgrade to a newer Node.js version in order to use this version of npm. This
  version of npm supports the following node versions: `^14.17.0 || ^16.13.0 ||`
  `>=18.0.0`. You can find the latest version at https://nodejs.org/.

  ERROR:
  /opt/hostedtoolcache/node/12.22.12/x64/lib/node_modules/npm/lib/utils/exit-handler.js:22
    const hasLoadedNpm = npm?.config.loaded
                           ^
  SyntaxError: Unexpected token '.'